service: dt2018

provider:
  name: aws
  stage: production
  region: eu-west-1
  runtime: nodejs8.10
  memorySize: 512
  environment:
    AWS_STAGE_URL_PREFIX: /production
    OFFLINE_LAMBDA_TASK_ROOT: true

plugins:
  - serverless-offline

functions:
  htmlIndex:
    handler: bot.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /styles.css
          method: get
          cors: true

  slackAuth:
    handler: bot.handler
    events:
      - http:
          path: /login
          method: get
      - http:
          path: /oauth
          method: get
      - http:
          path: /login_success.html
          method: get
      - http:
          path: /login_error.html
          method: get

  slackWebhooks:
    handler: bot.handler
    events:    
      - http:
          path: /slack/receive
          method: post
